# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lowKincpp <- function(P1, P2, adjust, domi, constr) {
    .Call(`_LoKi_lowKincpp`, P1, P2, adjust, domi, constr)
}

mmult <- function(m1) {
    .Call(`_LoKi_mmult`, m1)
}

test_vcf_reader <- function(filename) {
    .Call(`_LoKi_test_vcf_reader`, filename)
}

bebopalula <- function(s) {
    .Call(`_LoKi_bebopalula`, s)
}

