# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PartialKinVcfClassic <- function(filename, Index, field, q, adjust, domi, constr) {
    .Call(`_LowKi_PartialKinVcfClassic`, filename, Index, field, q, adjust, domi, constr)
}

RawKinVcfClassic <- function(filename, field, q, domi) {
    .Call(`_LowKi_RawKinVcfClassic`, filename, field, q, domi)
}

PartialKinVcfLoki <- function(filename, Index, field, adjust, domi, constr) {
    .Call(`_LowKi_PartialKinVcfLoki`, filename, Index, field, adjust, domi, constr)
}

RawKinVcfLoki <- function(filename, field, domi) {
    .Call(`_LowKi_RawKinVcfLoki`, filename, field, domi)
}

vcfAlleleFreqAD <- function(filename) {
    .Call(`_LowKi_vcfAlleleFreqAD`, filename)
}

vcfAlleleFreqPr <- function(filename, field) {
    .Call(`_LowKi_vcfAlleleFreqPr`, filename, field)
}

