# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lowKincpp <- function(P1, P2, adjust, domi, constr) {
    .Call(`_LoKi_lowKincpp`, P1, P2, adjust, domi, constr)
}

mmult <- function(m1) {
    .Call(`_LoKi_mmult`, m1)
}

read_dose_file <- function(filename) {
    .Call(`_LoKi_read_dose_file`, filename)
}

dose_file_dim <- function(filename) {
    .Call(`_LoKi_dose_file_dim`, filename)
}

nb_inds_dose_file <- function(filename) {
    .Call(`_LoKi_nb_inds_dose_file`, filename)
}

samples_dose_file <- function(filename) {
    .Call(`_LoKi_samples_dose_file`, filename)
}

read_vcf_head <- function(filename) {
    .Call(`_LoKi_read_vcf_head`, filename)
}

test_vcf_reader <- function(filename) {
    .Call(`_LoKi_test_vcf_reader`, filename)
}

